/**
 * Company-wide contract catalog. Every repo tagged cbd-publisher is cloned into
 * repos/ by `pnpm run repos`; nothing here names a publishing repo.
 */
import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const reposDir = join(process.env.PROJECT_DIR || process.cwd(), 'repos');
const repos = existsSync(reposDir) ? readdirSync(reposDir).sort() : [];
const has = (repo, path) => existsSync(join(reposDir, repo, path));

export default {
  cId: 'ymnn-a-monorepo-demo',
  // required by eventcatalog
  tsd: 1790425528643,
  title: 'Acme Contract Catalog',
  tagline: 'Every contract from every repo, one place',
  organizationName: 'Acme',
  homepageLink: 'https://jagreehal.github.io/cbd-docs-site/',
  port: 3000,
  outDir: 'dist',
  base: '/cbd-catalog',
  trailingSlash: false,
  auth: {
    enabled: false,
  },
  // Every doc under a repo's docs/ root becomes a page here. One autogenerated
  // sidebar group per publishing repo, so the reader sees who owns what.
  customDocs: {
    sidebar: repos
      .filter((repo) => has(repo, 'docs'))
      .map((repo) => ({ label: repo, collapsed: false, autogenerated: { directory: `/${repo}` } })),
  },
  generators: [
    [
      './generators/contracts.mjs',
      {
        repos: repos.filter((repo) => has(repo, 'contracts/events')).map((repo) => `repos/${repo}`),
        domain: {
          id: 'payments',
          name: 'Payments',
          version: '1.0.0',
          summary: 'HTTP and event contracts shared across repositories, languages, and transports.',
          markdown: [
            'The dashboard generates a typed frontend client from the payments OpenAPI artifact.',
            'Event consumers validate the committed JSON Schema payloads after their transport adapter removes any Kafka, NATS, SQS, RabbitMQ, EventBridge, or NDJSON envelope.',
            'Payload schemas stay stable when delivery infrastructure changes. Topics, subjects, queues, routing, retries, and acknowledgements belong to the transport contract.',
          ].join('\n\n'),
        },
      },
    ],
    [
      './generators/docs.mjs',
      {
        // the docs/ root of every publishing repo, engineering or not
        repos: repos.filter((repo) => has(repo, 'docs')).map((repo) => `repos/${repo}`),
      },
    ],
  ],
};
